#!/bin/bash

OUTPUT_FILE="../site.js"
TEMP_FILE="${OUTPUT_FILE}.tmp"
VERSION_FILE=".site-version"
PROJECT_ROOT="../.."

echo "Generating bundled site.js..."

if [ -f "${VERSION_FILE}" ]; then
  CURRENT_VERSION=$(cat "${VERSION_FILE}")
else
  CURRENT_VERSION=0
fi

NEW_VERSION=$((CURRENT_VERSION + 1))
echo "  Version: ${CURRENT_VERSION} → ${NEW_VERSION}"
echo ""

HELPERS=(
  "helper.js"
  "helper-api.js"
  "form-validator.js"
)

> "${TEMP_FILE}"

echo "// Bundled site.js - Generated by generate-site.sh at $(date '+%Y-%m-%d %H:%M:%S')" >> "${TEMP_FILE}"

for helper in "${HELPERS[@]}"; do
  if [ -f "${helper}" ]; then
    cat "${helper}" >> "${TEMP_FILE}"
    echo "  ✓ Added: ${helper}"
  else
    echo "  ✗ WARNING: ${helper} not found, skipping..."
  fi
done

echo ""
echo "Minifying JavaScript to single line..."

sed -E '
  s#^[ \t]*//.*$##
  s#[ \t]+//[^"].*$##
  s/^[ \t]+//
  s/[ \t]+$//
  /^$/d
' "${TEMP_FILE}" | tr '\n' ' ' | sed -E '
  s/  +/ /g
  s/ *; */;/g
  s/ +,/,/g
  s/$/\n/
' > "${OUTPUT_FILE}"

rm -f "${TEMP_FILE}"

echo "  ✓ Minified with sed"
echo ""
echo "✓ Successfully generated ${OUTPUT_FILE}"
echo "  File size: $(wc -c < "${OUTPUT_FILE}") bytes"
echo ""

echo "Updating script and CSS tags in HTML files..."
HTML_COUNT=0
CSS_COUNT=0

for html_file in "${PROJECT_ROOT}"/*.html; do
  if [ -f "${html_file}" ]; then
    if grep -q 'src="./s/site\.js' "${html_file}"; then
      sed -i -E 's#src="./s/site\.js(\?v=[0-9]+)?"#src="./s/site.js?v='"${NEW_VERSION}"'"#g' "${html_file}"
      ((HTML_COUNT++))
    fi

    if grep -q 'src="./s/code/pages/' "${html_file}"; then
      sed -i -E 's#src="(./s/code/pages/[^"]+\.js)(\?v=[0-9]+)?"#src="\1?v='"${NEW_VERSION}"'"#g' "${html_file}"
    fi

    if grep -q 'href="./s/site\.css' "${html_file}"; then
      sed -i -E 's#href="./s/site\.css(\?v=[0-9]+)?"#href="./s/site.css?v='"${NEW_VERSION}"'"#g' "${html_file}"
      ((CSS_COUNT++))
    fi

    sed -i -E '/<script src="\.\/s\/code\/helper[^"]*"[^>]*><\/script>/d' "${html_file}"
  fi
done

echo "  ✓ Updated ${HTML_COUNT} HTML files (JS)"
echo "  ✓ Updated ${CSS_COUNT} HTML files (CSS)"
echo "  ✓ Removed individual helper script tags"

echo "${NEW_VERSION}" > "${VERSION_FILE}"
echo "  ✓ Version saved: ${NEW_VERSION}"

echo ""
echo "All helpers are now bundled in correct order!"
echo "HTML files now use:"
echo "  <link rel=\"stylesheet\" href=\"./s/site.css?v=${NEW_VERSION}\" />"
echo "  <script src=\"./s/site.js?v=${NEW_VERSION}\"></script>"
